# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Guess', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RedsData',
            fields=[
                ('lastGamePlayed', models.DateField(primary_key=True, serialize=False)),
                ('won', models.IntegerField(default=0)),
                ('lost', models.IntegerField(default=0)),
            ],
        ),
    ]
